[package]
name = "messages"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-io-async = "0.7.0"
heapless = "0.7.*"
postcard = "1.1.3"
serde = { version = "1.0.228", default-features = false }
