[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --log-format defmt -p COM7"

[alias]
monitor = "espflash monitor --chip esp32 --log-format defmt --elf target\\xtensa-esp32-none-elf\\release\\rcs-controller"

[env]
DEFMT_LOG = "info"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
